# Generated by Django 2.1.5 on 2019-02-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_auto_20190205_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='confirmed',
            field=models.IntegerField(default=0),
        ),
    ]
